// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs3/publicshare/v0alpha/publicshare.proto

package publicsharev0alphapb

import (
	context "context"
	fmt "fmt"
	rpc "github.com/cernbox/go-cs3apis/cs3/rpc"
	sharetypes "github.com/cernbox/go-cs3apis/cs3/sharetypes"
	v0alpha "github.com/cernbox/go-cs3apis/cs3/storageprovider/v0alpha"
	types "github.com/cernbox/go-cs3apis/cs3/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListPublicSharesRequest_Filter_Type int32

const (
	ListPublicSharesRequest_Filter_TYPE_INVALID     ListPublicSharesRequest_Filter_Type = 0
	ListPublicSharesRequest_Filter_TYPE_RESOURCE_ID ListPublicSharesRequest_Filter_Type = 1
	ListPublicSharesRequest_Filter_TYPE_OWNER       ListPublicSharesRequest_Filter_Type = 2
	ListPublicSharesRequest_Filter_TYPE_CREATOR     ListPublicSharesRequest_Filter_Type = 3
)

var ListPublicSharesRequest_Filter_Type_name = map[int32]string{
	0: "TYPE_INVALID",
	1: "TYPE_RESOURCE_ID",
	2: "TYPE_OWNER",
	3: "TYPE_CREATOR",
}

var ListPublicSharesRequest_Filter_Type_value = map[string]int32{
	"TYPE_INVALID":     0,
	"TYPE_RESOURCE_ID": 1,
	"TYPE_OWNER":       2,
	"TYPE_CREATOR":     3,
}

func (x ListPublicSharesRequest_Filter_Type) String() string {
	return proto.EnumName(ListPublicSharesRequest_Filter_Type_name, int32(x))
}

func (ListPublicSharesRequest_Filter_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{6, 0, 0}
}

type GetProviderRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque               *types.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetProviderRequest) Reset()         { *m = GetProviderRequest{} }
func (m *GetProviderRequest) String() string { return proto.CompactTextString(m) }
func (*GetProviderRequest) ProtoMessage()    {}
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{0}
}

func (m *GetProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProviderRequest.Unmarshal(m, b)
}
func (m *GetProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProviderRequest.Marshal(b, m, deterministic)
}
func (m *GetProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProviderRequest.Merge(m, src)
}
func (m *GetProviderRequest) XXX_Size() int {
	return xxx_messageInfo_GetProviderRequest.Size(m)
}
func (m *GetProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProviderRequest proto.InternalMessageInfo

func (m *GetProviderRequest) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

type GetProviderResponse struct {
	// REQUIRED.
	// The response status.
	Status *rpc.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The information for the share provider.
	Info                 *sharetypes.ProviderInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetProviderResponse) Reset()         { *m = GetProviderResponse{} }
func (m *GetProviderResponse) String() string { return proto.CompactTextString(m) }
func (*GetProviderResponse) ProtoMessage()    {}
func (*GetProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{1}
}

func (m *GetProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProviderResponse.Unmarshal(m, b)
}
func (m *GetProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProviderResponse.Marshal(b, m, deterministic)
}
func (m *GetProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProviderResponse.Merge(m, src)
}
func (m *GetProviderResponse) XXX_Size() int {
	return xxx_messageInfo_GetProviderResponse.Size(m)
}
func (m *GetProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProviderResponse proto.InternalMessageInfo

func (m *GetProviderResponse) GetStatus() *rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetProviderResponse) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetProviderResponse) GetInfo() *sharetypes.ProviderInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type CreatePublicShareRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The unique identifier for the shared storage resource.
	ResourceId *v0alpha.ResourceId `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// REQUIRED.
	// The permissions for the share.
	Permissions *PublicSharePermissions `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// OPTIONAL.
	// A password to protect the access to the public share.
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// OPTIONAL.
	// An expiration date to protect the access to the public share.
	Expiration           *types.Timestamp `protobuf:"bytes,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreatePublicShareRequest) Reset()         { *m = CreatePublicShareRequest{} }
func (m *CreatePublicShareRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePublicShareRequest) ProtoMessage()    {}
func (*CreatePublicShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{2}
}

func (m *CreatePublicShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePublicShareRequest.Unmarshal(m, b)
}
func (m *CreatePublicShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePublicShareRequest.Marshal(b, m, deterministic)
}
func (m *CreatePublicShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePublicShareRequest.Merge(m, src)
}
func (m *CreatePublicShareRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePublicShareRequest.Size(m)
}
func (m *CreatePublicShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePublicShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePublicShareRequest proto.InternalMessageInfo

func (m *CreatePublicShareRequest) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *CreatePublicShareRequest) GetResourceId() *v0alpha.ResourceId {
	if m != nil {
		return m.ResourceId
	}
	return nil
}

func (m *CreatePublicShareRequest) GetPermissions() *PublicSharePermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *CreatePublicShareRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreatePublicShareRequest) GetExpiration() *types.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type CreatePublicShareResponse struct {
	// REQUIRED.
	// The response status.
	Status *rpc.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The created share.
	Share                *PublicShare `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreatePublicShareResponse) Reset()         { *m = CreatePublicShareResponse{} }
func (m *CreatePublicShareResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePublicShareResponse) ProtoMessage()    {}
func (*CreatePublicShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{3}
}

func (m *CreatePublicShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePublicShareResponse.Unmarshal(m, b)
}
func (m *CreatePublicShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePublicShareResponse.Marshal(b, m, deterministic)
}
func (m *CreatePublicShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePublicShareResponse.Merge(m, src)
}
func (m *CreatePublicShareResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePublicShareResponse.Size(m)
}
func (m *CreatePublicShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePublicShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePublicShareResponse proto.InternalMessageInfo

func (m *CreatePublicShareResponse) GetStatus() *rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreatePublicShareResponse) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *CreatePublicShareResponse) GetShare() *PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

type UpdatePublicShareRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The reference to the public share.
	Ref *PublicShareReference `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	// REQUIRED.
	// The field to be updated.
	Field                *UpdatePublicShareRequest_UpdateField `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *UpdatePublicShareRequest) Reset()         { *m = UpdatePublicShareRequest{} }
func (m *UpdatePublicShareRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePublicShareRequest) ProtoMessage()    {}
func (*UpdatePublicShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{4}
}

func (m *UpdatePublicShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePublicShareRequest.Unmarshal(m, b)
}
func (m *UpdatePublicShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePublicShareRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePublicShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePublicShareRequest.Merge(m, src)
}
func (m *UpdatePublicShareRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePublicShareRequest.Size(m)
}
func (m *UpdatePublicShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePublicShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePublicShareRequest proto.InternalMessageInfo

func (m *UpdatePublicShareRequest) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *UpdatePublicShareRequest) GetRef() *PublicShareReference {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *UpdatePublicShareRequest) GetField() *UpdatePublicShareRequest_UpdateField {
	if m != nil {
		return m.Field
	}
	return nil
}

// Available fields to update.
type UpdatePublicShareRequest_UpdateField struct {
	// One of the update fields MUST be specified.
	//
	// Types that are valid to be assigned to Field:
	//	*UpdatePublicShareRequest_UpdateField_Permissions
	//	*UpdatePublicShareRequest_UpdateField_Password
	//	*UpdatePublicShareRequest_UpdateField_Expiration
	Field                isUpdatePublicShareRequest_UpdateField_Field `protobuf_oneof:"field"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *UpdatePublicShareRequest_UpdateField) Reset()         { *m = UpdatePublicShareRequest_UpdateField{} }
func (m *UpdatePublicShareRequest_UpdateField) String() string { return proto.CompactTextString(m) }
func (*UpdatePublicShareRequest_UpdateField) ProtoMessage()    {}
func (*UpdatePublicShareRequest_UpdateField) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{4, 0}
}

func (m *UpdatePublicShareRequest_UpdateField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePublicShareRequest_UpdateField.Unmarshal(m, b)
}
func (m *UpdatePublicShareRequest_UpdateField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePublicShareRequest_UpdateField.Marshal(b, m, deterministic)
}
func (m *UpdatePublicShareRequest_UpdateField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePublicShareRequest_UpdateField.Merge(m, src)
}
func (m *UpdatePublicShareRequest_UpdateField) XXX_Size() int {
	return xxx_messageInfo_UpdatePublicShareRequest_UpdateField.Size(m)
}
func (m *UpdatePublicShareRequest_UpdateField) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePublicShareRequest_UpdateField.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePublicShareRequest_UpdateField proto.InternalMessageInfo

type isUpdatePublicShareRequest_UpdateField_Field interface {
	isUpdatePublicShareRequest_UpdateField_Field()
}

type UpdatePublicShareRequest_UpdateField_Permissions struct {
	Permissions *PublicSharePermissions `protobuf:"bytes,2,opt,name=permissions,proto3,oneof"`
}

type UpdatePublicShareRequest_UpdateField_Password struct {
	Password string `protobuf:"bytes,3,opt,name=password,proto3,oneof"`
}

type UpdatePublicShareRequest_UpdateField_Expiration struct {
	Expiration *types.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3,oneof"`
}

func (*UpdatePublicShareRequest_UpdateField_Permissions) isUpdatePublicShareRequest_UpdateField_Field() {
}

func (*UpdatePublicShareRequest_UpdateField_Password) isUpdatePublicShareRequest_UpdateField_Field() {}

func (*UpdatePublicShareRequest_UpdateField_Expiration) isUpdatePublicShareRequest_UpdateField_Field() {
}

func (m *UpdatePublicShareRequest_UpdateField) GetField() isUpdatePublicShareRequest_UpdateField_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *UpdatePublicShareRequest_UpdateField) GetPermissions() *PublicSharePermissions {
	if x, ok := m.GetField().(*UpdatePublicShareRequest_UpdateField_Permissions); ok {
		return x.Permissions
	}
	return nil
}

func (m *UpdatePublicShareRequest_UpdateField) GetPassword() string {
	if x, ok := m.GetField().(*UpdatePublicShareRequest_UpdateField_Password); ok {
		return x.Password
	}
	return ""
}

func (m *UpdatePublicShareRequest_UpdateField) GetExpiration() *types.Timestamp {
	if x, ok := m.GetField().(*UpdatePublicShareRequest_UpdateField_Expiration); ok {
		return x.Expiration
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UpdatePublicShareRequest_UpdateField) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UpdatePublicShareRequest_UpdateField_Permissions)(nil),
		(*UpdatePublicShareRequest_UpdateField_Password)(nil),
		(*UpdatePublicShareRequest_UpdateField_Expiration)(nil),
	}
}

type UpdatePublicShareResponse struct {
	// REQUIRED.
	// The response status.
	Status *rpc.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The updated public share.
	Share                *PublicShare `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdatePublicShareResponse) Reset()         { *m = UpdatePublicShareResponse{} }
func (m *UpdatePublicShareResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePublicShareResponse) ProtoMessage()    {}
func (*UpdatePublicShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{5}
}

func (m *UpdatePublicShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePublicShareResponse.Unmarshal(m, b)
}
func (m *UpdatePublicShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePublicShareResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePublicShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePublicShareResponse.Merge(m, src)
}
func (m *UpdatePublicShareResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePublicShareResponse.Size(m)
}
func (m *UpdatePublicShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePublicShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePublicShareResponse proto.InternalMessageInfo

func (m *UpdatePublicShareResponse) GetStatus() *rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpdatePublicShareResponse) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *UpdatePublicShareResponse) GetShare() *PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

type ListPublicSharesRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// OPTIONAL.
	// The list of filters to apply if any.
	Filters              []*ListPublicSharesRequest_Filter `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListPublicSharesRequest) Reset()         { *m = ListPublicSharesRequest{} }
func (m *ListPublicSharesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPublicSharesRequest) ProtoMessage()    {}
func (*ListPublicSharesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{6}
}

func (m *ListPublicSharesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublicSharesRequest.Unmarshal(m, b)
}
func (m *ListPublicSharesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublicSharesRequest.Marshal(b, m, deterministic)
}
func (m *ListPublicSharesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublicSharesRequest.Merge(m, src)
}
func (m *ListPublicSharesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPublicSharesRequest.Size(m)
}
func (m *ListPublicSharesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublicSharesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublicSharesRequest proto.InternalMessageInfo

func (m *ListPublicSharesRequest) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *ListPublicSharesRequest) GetFilters() []*ListPublicSharesRequest_Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

// represents a filter to apply to the request.
type ListPublicSharesRequest_Filter struct {
	Type ListPublicSharesRequest_Filter_Type `protobuf:"varint,2,opt,name=type,proto3,enum=cs3.publicsharev0alpha.ListPublicSharesRequest_Filter_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Term:
	//	*ListPublicSharesRequest_Filter_ResourceId
	//	*ListPublicSharesRequest_Filter_Owner
	//	*ListPublicSharesRequest_Filter_Creator
	Term                 isListPublicSharesRequest_Filter_Term `protobuf_oneof:"Term"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ListPublicSharesRequest_Filter) Reset()         { *m = ListPublicSharesRequest_Filter{} }
func (m *ListPublicSharesRequest_Filter) String() string { return proto.CompactTextString(m) }
func (*ListPublicSharesRequest_Filter) ProtoMessage()    {}
func (*ListPublicSharesRequest_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{6, 0}
}

func (m *ListPublicSharesRequest_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublicSharesRequest_Filter.Unmarshal(m, b)
}
func (m *ListPublicSharesRequest_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublicSharesRequest_Filter.Marshal(b, m, deterministic)
}
func (m *ListPublicSharesRequest_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublicSharesRequest_Filter.Merge(m, src)
}
func (m *ListPublicSharesRequest_Filter) XXX_Size() int {
	return xxx_messageInfo_ListPublicSharesRequest_Filter.Size(m)
}
func (m *ListPublicSharesRequest_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublicSharesRequest_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublicSharesRequest_Filter proto.InternalMessageInfo

func (m *ListPublicSharesRequest_Filter) GetType() ListPublicSharesRequest_Filter_Type {
	if m != nil {
		return m.Type
	}
	return ListPublicSharesRequest_Filter_TYPE_INVALID
}

type isListPublicSharesRequest_Filter_Term interface {
	isListPublicSharesRequest_Filter_Term()
}

type ListPublicSharesRequest_Filter_ResourceId struct {
	ResourceId *v0alpha.ResourceId `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3,oneof"`
}

type ListPublicSharesRequest_Filter_Owner struct {
	Owner *types.UserId `protobuf:"bytes,4,opt,name=owner,proto3,oneof"`
}

type ListPublicSharesRequest_Filter_Creator struct {
	Creator *types.UserId `protobuf:"bytes,5,opt,name=creator,proto3,oneof"`
}

func (*ListPublicSharesRequest_Filter_ResourceId) isListPublicSharesRequest_Filter_Term() {}

func (*ListPublicSharesRequest_Filter_Owner) isListPublicSharesRequest_Filter_Term() {}

func (*ListPublicSharesRequest_Filter_Creator) isListPublicSharesRequest_Filter_Term() {}

func (m *ListPublicSharesRequest_Filter) GetTerm() isListPublicSharesRequest_Filter_Term {
	if m != nil {
		return m.Term
	}
	return nil
}

func (m *ListPublicSharesRequest_Filter) GetResourceId() *v0alpha.ResourceId {
	if x, ok := m.GetTerm().(*ListPublicSharesRequest_Filter_ResourceId); ok {
		return x.ResourceId
	}
	return nil
}

func (m *ListPublicSharesRequest_Filter) GetOwner() *types.UserId {
	if x, ok := m.GetTerm().(*ListPublicSharesRequest_Filter_Owner); ok {
		return x.Owner
	}
	return nil
}

func (m *ListPublicSharesRequest_Filter) GetCreator() *types.UserId {
	if x, ok := m.GetTerm().(*ListPublicSharesRequest_Filter_Creator); ok {
		return x.Creator
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListPublicSharesRequest_Filter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListPublicSharesRequest_Filter_ResourceId)(nil),
		(*ListPublicSharesRequest_Filter_Owner)(nil),
		(*ListPublicSharesRequest_Filter_Creator)(nil),
	}
}

type ListPublicSharesResponse struct {
	// REQUIRED.
	// The response status.
	Status *rpc.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The list of shares.
	Share                []*PublicShare `protobuf:"bytes,3,rep,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPublicSharesResponse) Reset()         { *m = ListPublicSharesResponse{} }
func (m *ListPublicSharesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPublicSharesResponse) ProtoMessage()    {}
func (*ListPublicSharesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{7}
}

func (m *ListPublicSharesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublicSharesResponse.Unmarshal(m, b)
}
func (m *ListPublicSharesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublicSharesResponse.Marshal(b, m, deterministic)
}
func (m *ListPublicSharesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublicSharesResponse.Merge(m, src)
}
func (m *ListPublicSharesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPublicSharesResponse.Size(m)
}
func (m *ListPublicSharesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublicSharesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublicSharesResponse proto.InternalMessageInfo

func (m *ListPublicSharesResponse) GetStatus() *rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPublicSharesResponse) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *ListPublicSharesResponse) GetShare() []*PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

type RemovePublicShareRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The reference to which the action should be performed.
	Ref                  *PublicShareReference `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RemovePublicShareRequest) Reset()         { *m = RemovePublicShareRequest{} }
func (m *RemovePublicShareRequest) String() string { return proto.CompactTextString(m) }
func (*RemovePublicShareRequest) ProtoMessage()    {}
func (*RemovePublicShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{8}
}

func (m *RemovePublicShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePublicShareRequest.Unmarshal(m, b)
}
func (m *RemovePublicShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePublicShareRequest.Marshal(b, m, deterministic)
}
func (m *RemovePublicShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePublicShareRequest.Merge(m, src)
}
func (m *RemovePublicShareRequest) XXX_Size() int {
	return xxx_messageInfo_RemovePublicShareRequest.Size(m)
}
func (m *RemovePublicShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePublicShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePublicShareRequest proto.InternalMessageInfo

func (m *RemovePublicShareRequest) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *RemovePublicShareRequest) GetRef() *PublicShareReference {
	if m != nil {
		return m.Ref
	}
	return nil
}

type RemovePublicShareResponse struct {
	// REQUIRED.
	// The response status.
	Status *rpc.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque               *types.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RemovePublicShareResponse) Reset()         { *m = RemovePublicShareResponse{} }
func (m *RemovePublicShareResponse) String() string { return proto.CompactTextString(m) }
func (*RemovePublicShareResponse) ProtoMessage()    {}
func (*RemovePublicShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{9}
}

func (m *RemovePublicShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePublicShareResponse.Unmarshal(m, b)
}
func (m *RemovePublicShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePublicShareResponse.Marshal(b, m, deterministic)
}
func (m *RemovePublicShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePublicShareResponse.Merge(m, src)
}
func (m *RemovePublicShareResponse) XXX_Size() int {
	return xxx_messageInfo_RemovePublicShareResponse.Size(m)
}
func (m *RemovePublicShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePublicShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePublicShareResponse proto.InternalMessageInfo

func (m *RemovePublicShareResponse) GetStatus() *rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RemovePublicShareResponse) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

type GetPublicShareRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The reference to which the action should be performed.
	Ref                  *PublicShareReference `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetPublicShareRequest) Reset()         { *m = GetPublicShareRequest{} }
func (m *GetPublicShareRequest) String() string { return proto.CompactTextString(m) }
func (*GetPublicShareRequest) ProtoMessage()    {}
func (*GetPublicShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{10}
}

func (m *GetPublicShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicShareRequest.Unmarshal(m, b)
}
func (m *GetPublicShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicShareRequest.Marshal(b, m, deterministic)
}
func (m *GetPublicShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicShareRequest.Merge(m, src)
}
func (m *GetPublicShareRequest) XXX_Size() int {
	return xxx_messageInfo_GetPublicShareRequest.Size(m)
}
func (m *GetPublicShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicShareRequest proto.InternalMessageInfo

func (m *GetPublicShareRequest) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetPublicShareRequest) GetRef() *PublicShareReference {
	if m != nil {
		return m.Ref
	}
	return nil
}

type GetPublicShareResponse struct {
	// REQUIRED.
	// The response status.
	Status *rpc.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The share.
	Share                *PublicShare `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPublicShareResponse) Reset()         { *m = GetPublicShareResponse{} }
func (m *GetPublicShareResponse) String() string { return proto.CompactTextString(m) }
func (*GetPublicShareResponse) ProtoMessage()    {}
func (*GetPublicShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{11}
}

func (m *GetPublicShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicShareResponse.Unmarshal(m, b)
}
func (m *GetPublicShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicShareResponse.Marshal(b, m, deterministic)
}
func (m *GetPublicShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicShareResponse.Merge(m, src)
}
func (m *GetPublicShareResponse) XXX_Size() int {
	return xxx_messageInfo_GetPublicShareResponse.Size(m)
}
func (m *GetPublicShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicShareResponse proto.InternalMessageInfo

func (m *GetPublicShareResponse) GetStatus() *rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetPublicShareResponse) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetPublicShareResponse) GetShare() *PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

type GetPublicShareByTokenRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The unlisted token to identify the public share.
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPublicShareByTokenRequest) Reset()         { *m = GetPublicShareByTokenRequest{} }
func (m *GetPublicShareByTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetPublicShareByTokenRequest) ProtoMessage()    {}
func (*GetPublicShareByTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{12}
}

func (m *GetPublicShareByTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicShareByTokenRequest.Unmarshal(m, b)
}
func (m *GetPublicShareByTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicShareByTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetPublicShareByTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicShareByTokenRequest.Merge(m, src)
}
func (m *GetPublicShareByTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetPublicShareByTokenRequest.Size(m)
}
func (m *GetPublicShareByTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicShareByTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicShareByTokenRequest proto.InternalMessageInfo

func (m *GetPublicShareByTokenRequest) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetPublicShareByTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetPublicShareByTokenResponse struct {
	// REQUIRED.
	// The response status.
	Status *rpc.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *types.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The share.
	Share                *PublicShare `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPublicShareByTokenResponse) Reset()         { *m = GetPublicShareByTokenResponse{} }
func (m *GetPublicShareByTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetPublicShareByTokenResponse) ProtoMessage()    {}
func (*GetPublicShareByTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce037002abb23640, []int{13}
}

func (m *GetPublicShareByTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicShareByTokenResponse.Unmarshal(m, b)
}
func (m *GetPublicShareByTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicShareByTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetPublicShareByTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicShareByTokenResponse.Merge(m, src)
}
func (m *GetPublicShareByTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetPublicShareByTokenResponse.Size(m)
}
func (m *GetPublicShareByTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicShareByTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicShareByTokenResponse proto.InternalMessageInfo

func (m *GetPublicShareByTokenResponse) GetStatus() *rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetPublicShareByTokenResponse) GetOpaque() *types.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetPublicShareByTokenResponse) GetShare() *PublicShare {
	if m != nil {
		return m.Share
	}
	return nil
}

func init() {
	proto.RegisterEnum("cs3.publicsharev0alpha.ListPublicSharesRequest_Filter_Type", ListPublicSharesRequest_Filter_Type_name, ListPublicSharesRequest_Filter_Type_value)
	proto.RegisterType((*GetProviderRequest)(nil), "cs3.publicsharev0alpha.GetProviderRequest")
	proto.RegisterType((*GetProviderResponse)(nil), "cs3.publicsharev0alpha.GetProviderResponse")
	proto.RegisterType((*CreatePublicShareRequest)(nil), "cs3.publicsharev0alpha.CreatePublicShareRequest")
	proto.RegisterType((*CreatePublicShareResponse)(nil), "cs3.publicsharev0alpha.CreatePublicShareResponse")
	proto.RegisterType((*UpdatePublicShareRequest)(nil), "cs3.publicsharev0alpha.UpdatePublicShareRequest")
	proto.RegisterType((*UpdatePublicShareRequest_UpdateField)(nil), "cs3.publicsharev0alpha.UpdatePublicShareRequest.UpdateField")
	proto.RegisterType((*UpdatePublicShareResponse)(nil), "cs3.publicsharev0alpha.UpdatePublicShareResponse")
	proto.RegisterType((*ListPublicSharesRequest)(nil), "cs3.publicsharev0alpha.ListPublicSharesRequest")
	proto.RegisterType((*ListPublicSharesRequest_Filter)(nil), "cs3.publicsharev0alpha.ListPublicSharesRequest.Filter")
	proto.RegisterType((*ListPublicSharesResponse)(nil), "cs3.publicsharev0alpha.ListPublicSharesResponse")
	proto.RegisterType((*RemovePublicShareRequest)(nil), "cs3.publicsharev0alpha.RemovePublicShareRequest")
	proto.RegisterType((*RemovePublicShareResponse)(nil), "cs3.publicsharev0alpha.RemovePublicShareResponse")
	proto.RegisterType((*GetPublicShareRequest)(nil), "cs3.publicsharev0alpha.GetPublicShareRequest")
	proto.RegisterType((*GetPublicShareResponse)(nil), "cs3.publicsharev0alpha.GetPublicShareResponse")
	proto.RegisterType((*GetPublicShareByTokenRequest)(nil), "cs3.publicsharev0alpha.GetPublicShareByTokenRequest")
	proto.RegisterType((*GetPublicShareByTokenResponse)(nil), "cs3.publicsharev0alpha.GetPublicShareByTokenResponse")
}

func init() {
	proto.RegisterFile("cs3/publicshare/v0alpha/publicshare.proto", fileDescriptor_ce037002abb23640)
}

var fileDescriptor_ce037002abb23640 = []byte{
	// 961 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xce, 0xfa, 0x2f, 0xe4, 0x18, 0x05, 0x77, 0x70, 0x83, 0xbb, 0x0a, 0xa2, 0x5a, 0x24, 0x9a,
	0x50, 0xba, 0x31, 0x49, 0xa9, 0x84, 0x40, 0xa0, 0xd8, 0x75, 0x1b, 0x4b, 0x55, 0xbd, 0x1a, 0x3b,
	0xe5, 0x47, 0x48, 0xd1, 0x66, 0x3d, 0xa6, 0x2b, 0xe2, 0x9d, 0xed, 0xcc, 0x3a, 0x6d, 0x2e, 0x41,
	0xf0, 0x14, 0x70, 0xc5, 0x0d, 0xa2, 0x17, 0x5c, 0xf0, 0x04, 0x5c, 0xf3, 0x04, 0xdc, 0xf2, 0x08,
	0xbc, 0x01, 0x9a, 0xd9, 0x71, 0x32, 0xdb, 0xf5, 0x80, 0x1d, 0x54, 0x9a, 0x3b, 0xfb, 0xcc, 0x77,
	0xbe, 0x73, 0xe6, 0x9b, 0x6f, 0xcf, 0xce, 0xc2, 0x66, 0xc0, 0x77, 0xb6, 0xe2, 0xc9, 0xe1, 0x51,
	0x18, 0xf0, 0x87, 0x3e, 0x23, 0x5b, 0xc7, 0x4d, 0xff, 0x28, 0x7e, 0xe8, 0xeb, 0x31, 0x37, 0x66,
	0x34, 0xa1, 0x68, 0x2d, 0xe0, 0x3b, 0xae, 0x16, 0x56, 0x48, 0xfb, 0x9a, 0x89, 0x82, 0x11, 0x4e,
	0x27, 0x2c, 0x20, 0x3c, 0x25, 0xb0, 0xeb, 0x02, 0xc8, 0xe2, 0x60, 0x8b, 0x27, 0x7e, 0x32, 0x99,
	0x46, 0xdf, 0x10, 0x51, 0x99, 0x98, 0x9c, 0xc4, 0x84, 0x6b, 0x3f, 0x15, 0xe0, 0xba, 0x04, 0x24,
	0x94, 0xf9, 0x5f, 0x92, 0x98, 0xd1, 0xe3, 0x70, 0x48, 0x98, 0xb1, 0xc6, 0x65, 0x01, 0x4e, 0x89,
	0x34, 0x0e, 0xe7, 0x63, 0x40, 0x77, 0x49, 0xe2, 0xa9, 0x6c, 0x4c, 0x1e, 0x4d, 0x08, 0x4f, 0xd0,
	0x26, 0x54, 0x68, 0xec, 0x3f, 0x9a, 0x90, 0x86, 0x75, 0xd5, 0xda, 0xa8, 0x6e, 0x5f, 0x72, 0xc5,
	0x16, 0xd3, 0xbc, 0x9e, 0x5c, 0xc0, 0x0a, 0xe0, 0x7c, 0x6f, 0xc1, 0xab, 0x19, 0x06, 0x1e, 0xd3,
	0x88, 0x13, 0x74, 0x0d, 0x2a, 0xe9, 0x6e, 0x14, 0xc5, 0x2b, 0x92, 0x82, 0xc5, 0x81, 0xdb, 0x97,
	0x61, 0xac, 0x96, 0xb5, 0x5a, 0x85, 0x7f, 0xa9, 0x85, 0x9a, 0x50, 0x0a, 0xa3, 0x11, 0x6d, 0x14,
	0x25, 0x70, 0x5d, 0x02, 0x35, 0x55, 0xa6, 0x3d, 0x74, 0xa3, 0x11, 0xc5, 0x12, 0xe9, 0xfc, 0x5a,
	0x80, 0x46, 0x9b, 0x11, 0x3f, 0x21, 0x9e, 0x3c, 0x87, 0xbe, 0x40, 0x2f, 0xbe, 0x4b, 0x74, 0x17,
	0xaa, 0x53, 0x41, 0x0f, 0xc2, 0xa1, 0xea, 0xf4, 0xad, 0xb4, 0x81, 0xec, 0x01, 0x28, 0xfd, 0x5d,
	0xac, 0xe0, 0xdd, 0x21, 0x06, 0x76, 0xfa, 0x1b, 0x79, 0x50, 0x8d, 0x09, 0x1b, 0x87, 0x9c, 0x87,
	0x34, 0xe2, 0x6a, 0x27, 0xae, 0x3b, 0xdb, 0x41, 0xae, 0xd6, 0xb4, 0x77, 0x96, 0x85, 0x75, 0x0a,
	0x64, 0xc3, 0x4b, 0xb1, 0xcf, 0xf9, 0x63, 0xca, 0x86, 0x8d, 0xd2, 0x55, 0x6b, 0x63, 0x05, 0x9f,
	0xfe, 0x47, 0x37, 0x01, 0xc8, 0x93, 0x38, 0x64, 0x7e, 0x12, 0xd2, 0xa8, 0x51, 0x96, 0xc5, 0xea,
	0xda, 0x2e, 0x07, 0xe1, 0x98, 0xf0, 0xc4, 0x1f, 0xc7, 0x58, 0xc3, 0x39, 0x4f, 0x2d, 0xb8, 0x32,
	0x43, 0xb4, 0xe7, 0x78, 0xb0, 0xef, 0x43, 0x59, 0xee, 0x5b, 0xe9, 0xf1, 0xe6, 0x1c, 0x7a, 0xe0,
	0x34, 0xc3, 0xf9, 0xa1, 0x08, 0x8d, 0xfd, 0x78, 0xf8, 0x9f, 0x4f, 0xf8, 0x23, 0x28, 0x32, 0x32,
	0x52, 0xad, 0xbe, 0x33, 0x4f, 0x03, 0x64, 0x44, 0x18, 0x89, 0x02, 0x82, 0x45, 0x22, 0xc2, 0x50,
	0x1e, 0x85, 0xe4, 0x68, 0xa8, 0x54, 0xfe, 0xd0, 0xc4, 0x60, 0xea, 0x55, 0x2d, 0xdc, 0x11, 0x1c,
	0x38, 0xa5, 0xb2, 0x7f, 0xb3, 0xa0, 0xaa, 0x85, 0x11, 0xce, 0x9a, 0xa7, 0x70, 0x1e, 0xf3, 0xec,
	0x2d, 0x65, 0xed, 0xb3, 0xae, 0xd9, 0x47, 0xa8, 0xbf, 0xb2, 0xb7, 0xa4, 0x19, 0xe8, 0x56, 0xc6,
	0x40, 0x25, 0xb3, 0x81, 0xf6, 0x96, 0x74, 0x0b, 0xb5, 0x96, 0x95, 0x1a, 0xd2, 0x4b, 0x33, 0xb6,
	0x7c, 0x31, 0xbd, 0xf4, 0x57, 0x11, 0x5e, 0xbb, 0x17, 0xf2, 0x44, 0x5b, 0xe2, 0xe7, 0xb0, 0x92,
	0x07, 0xcb, 0xa3, 0xf0, 0x28, 0x21, 0x4c, 0x1c, 0x51, 0x71, 0xa3, 0xba, 0x7d, 0xcb, 0xd4, 0x83,
	0xa1, 0x98, 0x7b, 0x47, 0xa6, 0xe3, 0x29, 0x8d, 0xfd, 0x47, 0x01, 0x2a, 0x69, 0x0c, 0xf5, 0xa0,
	0x24, 0x8a, 0x4a, 0x1d, 0x56, 0xb7, 0x3f, 0x38, 0x1f, 0xb3, 0x3b, 0x38, 0x89, 0x09, 0x96, 0x44,
	0xa8, 0x9b, 0x1d, 0x6d, 0xc5, 0x45, 0x46, 0x9b, 0x38, 0x75, 0x6d, 0xb8, 0x6d, 0x42, 0x99, 0x3e,
	0x8e, 0x08, 0x53, 0x46, 0xd1, 0x25, 0xda, 0xe7, 0x84, 0x49, 0x7c, 0x8a, 0x40, 0x37, 0x60, 0x39,
	0x10, 0x23, 0x86, 0x32, 0xf5, 0xc0, 0xcc, 0x04, 0x4f, 0x31, 0x8e, 0x07, 0x25, 0xd1, 0x32, 0xaa,
	0xc1, 0xcb, 0x83, 0xcf, 0xbc, 0xce, 0x41, 0xf7, 0xfe, 0x83, 0xdd, 0x7b, 0xdd, 0xdb, 0xb5, 0x25,
	0x54, 0x87, 0x9a, 0x8c, 0xe0, 0x4e, 0xbf, 0xb7, 0x8f, 0xdb, 0x9d, 0x83, 0xee, 0xed, 0x9a, 0x85,
	0x56, 0x01, 0x64, 0xb4, 0xf7, 0xc9, 0xfd, 0x0e, 0xae, 0x15, 0x4e, 0xf3, 0xda, 0xb8, 0xb3, 0x3b,
	0xe8, 0xe1, 0x5a, 0xb1, 0x55, 0x81, 0xd2, 0x80, 0xb0, 0xb1, 0xf3, 0xb3, 0x05, 0x8d, 0xbc, 0x58,
	0xff, 0x8f, 0x3f, 0x8b, 0x0b, 0xfa, 0xf3, 0x3b, 0x0b, 0x1a, 0x98, 0x8c, 0xe9, 0xf1, 0x8b, 0x9d,
	0x75, 0x0e, 0x85, 0x2b, 0x33, 0xda, 0x78, 0x7e, 0x9a, 0x39, 0xdf, 0x58, 0x70, 0x59, 0x5c, 0x32,
	0x5e, 0xe8, 0xae, 0x7f, 0xb2, 0x60, 0xed, 0xd9, 0x26, 0x2e, 0xe6, 0x1c, 0x3b, 0x80, 0xf5, 0x6c,
	0xa3, 0xad, 0x93, 0x01, 0xfd, 0x8a, 0x44, 0xe7, 0x10, 0xad, 0x0e, 0xe5, 0x44, 0xa4, 0xca, 0x7e,
	0x57, 0x70, 0xfa, 0xc7, 0xf9, 0xc5, 0x82, 0xd7, 0x0d, 0x15, 0x2e, 0xa4, 0x22, 0xdb, 0x7f, 0x56,
	0xc0, 0xd6, 0xdf, 0x87, 0x6a, 0xa2, 0xf5, 0x09, 0x3b, 0x0e, 0x03, 0x82, 0x46, 0x50, 0xd5, 0xee,
	0xb0, 0xe8, 0x6d, 0x13, 0x73, 0xfe, 0xaa, 0x6c, 0x5f, 0x9f, 0x0b, 0xab, 0x54, 0x79, 0x02, 0x97,
	0x72, 0x17, 0x2b, 0xd4, 0x34, 0x31, 0x98, 0x2e, 0xae, 0xf6, 0xbb, 0x0b, 0x64, 0x9c, 0x55, 0xce,
	0x3d, 0xb2, 0xe6, 0xca, 0xa6, 0x21, 0x63, 0xae, 0x6c, 0x9e, 0x07, 0x14, 0x56, 0xb3, 0x56, 0x41,
	0x37, 0xfe, 0x49, 0xb2, 0x7c, 0x4d, 0x77, 0x5e, 0xb8, 0x2a, 0xf8, 0x6d, 0x6e, 0x58, 0x28, 0x73,
	0xa2, 0x9b, 0xf3, 0x31, 0x65, 0x9f, 0x16, 0xfb, 0xbd, 0x05, 0xb3, 0x54, 0x1b, 0x13, 0xa8, 0x3d,
	0xfb, 0x5e, 0x41, 0x5b, 0x0b, 0xbe, 0xae, 0xed, 0xe6, 0xfc, 0x09, 0x67, 0x07, 0x9d, 0xbb, 0x6f,
	0x99, 0x0f, 0xda, 0x74, 0x1b, 0x35, 0x1f, 0xb4, 0xf1, 0x32, 0xd7, 0xfa, 0xda, 0x02, 0x3b, 0xa0,
	0x63, 0x43, 0x62, 0xab, 0xe6, 0x9d, 0xc5, 0x3c, 0xf1, 0xed, 0xe9, 0x59, 0x9f, 0xd7, 0xf3, 0xb8,
	0xf8, 0xf0, 0xc7, 0x42, 0xa5, 0xdd, 0xea, 0x7d, 0xba, 0xdb, 0x7a, 0x5a, 0x58, 0x6b, 0xf7, 0x77,
	0xf4, 0xc7, 0xf9, 0x41, 0x73, 0x57, 0x60, 0x7e, 0x97, 0x0b, 0x5f, 0xe4, 0x17, 0x0e, 0x2b, 0xf2,
	0xab, 0x76, 0xe7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xba, 0xff, 0xef, 0xbe, 0x0f, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PublicShareProviderServiceClient is the client API for PublicShareProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublicShareProviderServiceClient interface {
	// Returns the information for this provider.
	GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*GetProviderResponse, error)
	// Creates a new share.
	// MUST return CODE_NOT_FOUND if the resource reference does not exist.
	// MUST return CODE_ALREADY_EXISTS if the share already exists for the 4-tuple consisting of
	// (owner, shared_resource, grantee).
	// New shares MUST be created in the state SHARE_STATE_PENDING.
	CreatePublicShare(ctx context.Context, in *CreatePublicShareRequest, opts ...grpc.CallOption) (*CreatePublicShareResponse, error)
	// Removes a share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	RemovePublicShare(ctx context.Context, in *RemovePublicShareRequest, opts ...grpc.CallOption) (*RemovePublicShareResponse, error)
	// Gets share information for a single share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	GetPublicShare(ctx context.Context, in *GetPublicShareRequest, opts ...grpc.CallOption) (*GetPublicShareResponse, error)
	// Gets share information for a single share by its unlisted token.
	// MUST return CODE_NOT_FOUND if the share does not exist.
	GetPublicShareByToken(ctx context.Context, in *GetPublicShareByTokenRequest, opts ...grpc.CallOption) (*GetPublicShareByTokenResponse, error)
	// List the shares the authenticated principal has created,
	// both as owner and creator. If a filter is specified, only
	// shares satisfying the filter MUST be returned.
	ListPublicShares(ctx context.Context, in *ListPublicSharesRequest, opts ...grpc.CallOption) (*ListPublicSharesResponse, error)
	// Updates a share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	UpdatePublicShare(ctx context.Context, in *UpdatePublicShareRequest, opts ...grpc.CallOption) (*UpdatePublicShareResponse, error)
}

type publicShareProviderServiceClient struct {
	cc *grpc.ClientConn
}

func NewPublicShareProviderServiceClient(cc *grpc.ClientConn) PublicShareProviderServiceClient {
	return &publicShareProviderServiceClient{cc}
}

func (c *publicShareProviderServiceClient) GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*GetProviderResponse, error) {
	out := new(GetProviderResponse)
	err := c.cc.Invoke(ctx, "/cs3.publicsharev0alpha.PublicShareProviderService/GetProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicShareProviderServiceClient) CreatePublicShare(ctx context.Context, in *CreatePublicShareRequest, opts ...grpc.CallOption) (*CreatePublicShareResponse, error) {
	out := new(CreatePublicShareResponse)
	err := c.cc.Invoke(ctx, "/cs3.publicsharev0alpha.PublicShareProviderService/CreatePublicShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicShareProviderServiceClient) RemovePublicShare(ctx context.Context, in *RemovePublicShareRequest, opts ...grpc.CallOption) (*RemovePublicShareResponse, error) {
	out := new(RemovePublicShareResponse)
	err := c.cc.Invoke(ctx, "/cs3.publicsharev0alpha.PublicShareProviderService/RemovePublicShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicShareProviderServiceClient) GetPublicShare(ctx context.Context, in *GetPublicShareRequest, opts ...grpc.CallOption) (*GetPublicShareResponse, error) {
	out := new(GetPublicShareResponse)
	err := c.cc.Invoke(ctx, "/cs3.publicsharev0alpha.PublicShareProviderService/GetPublicShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicShareProviderServiceClient) GetPublicShareByToken(ctx context.Context, in *GetPublicShareByTokenRequest, opts ...grpc.CallOption) (*GetPublicShareByTokenResponse, error) {
	out := new(GetPublicShareByTokenResponse)
	err := c.cc.Invoke(ctx, "/cs3.publicsharev0alpha.PublicShareProviderService/GetPublicShareByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicShareProviderServiceClient) ListPublicShares(ctx context.Context, in *ListPublicSharesRequest, opts ...grpc.CallOption) (*ListPublicSharesResponse, error) {
	out := new(ListPublicSharesResponse)
	err := c.cc.Invoke(ctx, "/cs3.publicsharev0alpha.PublicShareProviderService/ListPublicShares", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicShareProviderServiceClient) UpdatePublicShare(ctx context.Context, in *UpdatePublicShareRequest, opts ...grpc.CallOption) (*UpdatePublicShareResponse, error) {
	out := new(UpdatePublicShareResponse)
	err := c.cc.Invoke(ctx, "/cs3.publicsharev0alpha.PublicShareProviderService/UpdatePublicShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicShareProviderServiceServer is the server API for PublicShareProviderService service.
type PublicShareProviderServiceServer interface {
	// Returns the information for this provider.
	GetProvider(context.Context, *GetProviderRequest) (*GetProviderResponse, error)
	// Creates a new share.
	// MUST return CODE_NOT_FOUND if the resource reference does not exist.
	// MUST return CODE_ALREADY_EXISTS if the share already exists for the 4-tuple consisting of
	// (owner, shared_resource, grantee).
	// New shares MUST be created in the state SHARE_STATE_PENDING.
	CreatePublicShare(context.Context, *CreatePublicShareRequest) (*CreatePublicShareResponse, error)
	// Removes a share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	RemovePublicShare(context.Context, *RemovePublicShareRequest) (*RemovePublicShareResponse, error)
	// Gets share information for a single share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	GetPublicShare(context.Context, *GetPublicShareRequest) (*GetPublicShareResponse, error)
	// Gets share information for a single share by its unlisted token.
	// MUST return CODE_NOT_FOUND if the share does not exist.
	GetPublicShareByToken(context.Context, *GetPublicShareByTokenRequest) (*GetPublicShareByTokenResponse, error)
	// List the shares the authenticated principal has created,
	// both as owner and creator. If a filter is specified, only
	// shares satisfying the filter MUST be returned.
	ListPublicShares(context.Context, *ListPublicSharesRequest) (*ListPublicSharesResponse, error)
	// Updates a share.
	// MUST return CODE_NOT_FOUND if the share reference does not exist.
	UpdatePublicShare(context.Context, *UpdatePublicShareRequest) (*UpdatePublicShareResponse, error)
}

func RegisterPublicShareProviderServiceServer(s *grpc.Server, srv PublicShareProviderServiceServer) {
	s.RegisterService(&_PublicShareProviderService_serviceDesc, srv)
}

func _PublicShareProviderService_GetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicShareProviderServiceServer).GetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.publicsharev0alpha.PublicShareProviderService/GetProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicShareProviderServiceServer).GetProvider(ctx, req.(*GetProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicShareProviderService_CreatePublicShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePublicShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicShareProviderServiceServer).CreatePublicShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.publicsharev0alpha.PublicShareProviderService/CreatePublicShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicShareProviderServiceServer).CreatePublicShare(ctx, req.(*CreatePublicShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicShareProviderService_RemovePublicShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePublicShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicShareProviderServiceServer).RemovePublicShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.publicsharev0alpha.PublicShareProviderService/RemovePublicShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicShareProviderServiceServer).RemovePublicShare(ctx, req.(*RemovePublicShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicShareProviderService_GetPublicShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicShareProviderServiceServer).GetPublicShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.publicsharev0alpha.PublicShareProviderService/GetPublicShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicShareProviderServiceServer).GetPublicShare(ctx, req.(*GetPublicShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicShareProviderService_GetPublicShareByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicShareByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicShareProviderServiceServer).GetPublicShareByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.publicsharev0alpha.PublicShareProviderService/GetPublicShareByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicShareProviderServiceServer).GetPublicShareByToken(ctx, req.(*GetPublicShareByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicShareProviderService_ListPublicShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicShareProviderServiceServer).ListPublicShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.publicsharev0alpha.PublicShareProviderService/ListPublicShares",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicShareProviderServiceServer).ListPublicShares(ctx, req.(*ListPublicSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicShareProviderService_UpdatePublicShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePublicShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicShareProviderServiceServer).UpdatePublicShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.publicsharev0alpha.PublicShareProviderService/UpdatePublicShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicShareProviderServiceServer).UpdatePublicShare(ctx, req.(*UpdatePublicShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublicShareProviderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cs3.publicsharev0alpha.PublicShareProviderService",
	HandlerType: (*PublicShareProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProvider",
			Handler:    _PublicShareProviderService_GetProvider_Handler,
		},
		{
			MethodName: "CreatePublicShare",
			Handler:    _PublicShareProviderService_CreatePublicShare_Handler,
		},
		{
			MethodName: "RemovePublicShare",
			Handler:    _PublicShareProviderService_RemovePublicShare_Handler,
		},
		{
			MethodName: "GetPublicShare",
			Handler:    _PublicShareProviderService_GetPublicShare_Handler,
		},
		{
			MethodName: "GetPublicShareByToken",
			Handler:    _PublicShareProviderService_GetPublicShareByToken_Handler,
		},
		{
			MethodName: "ListPublicShares",
			Handler:    _PublicShareProviderService_ListPublicShares_Handler,
		},
		{
			MethodName: "UpdatePublicShare",
			Handler:    _PublicShareProviderService_UpdatePublicShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cs3/publicshare/v0alpha/publicshare.proto",
}
