# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install mockery
      run: go install github.com/vektra/mockery/v2@v2.40.0 # Later versions are incompatible with Go 1.21

    - name: Run mockery
      run: mockery

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
